language: ruby
script:
  - bundle exec rspec
matrix:
  fast_finish: true
  allow_failures:
  - name: TruffleRuby
    rvm: system
  include:
  - rvm: 2.3.0
    install:
      - gem install bundler --no-document
      - bundle install
  - rvm: 2.5.1
    install:
      - gem install bundler --no-document
      - bundle install
  - rvm: 2.6.0-preview3
    install:
      - bundle install
  - name: TruffleRuby
    rvm: system
    install:
      - export TRUFFLERUBY_VERSION=1.0.0-rc10
      - curl -L https://github.com/oracle/truffleruby/releases/download/vm-$TRUFFLERUBY_VERSION/truffleruby-$TRUFFLERUBY_VERSION-linux-amd64.tar.gz | tar xz
      - export PATH="$PWD/truffleruby-$TRUFFLERUBY_VERSION-linux-amd64/bin:$PATH"
      - gem install bundler -v 1.16.6 --no-ri --no-rdoc
      - bundle install
